### PR TITLE
Introduce tests, namespacing, precision rounding and optional exiting

### LINKED ISSUE #6: Add tests for action in a GitHub Wokflow
Ideally I would like to have some sort of automatic testing set up. Since it's quite time consuming to test this action manually :thinking:

_Originally posted by @johanvanhelden in https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/4#issuecomment-689826575_

### PR DESCRIPTION
**Pull request by johanvanhelden**
Adds:
- Tests
- Precision rounding
- Optional exiting

And cleans the code up a lot.

Fixes https://github.com/johanvanhelden/gha-clover-test-coverage-check/issues/6 and https://github.com/johanvanhelden/gha-clover-test-coverage-check/issues/5

### CODE REVIEW

**Comment by johanvanhelden** [comment]
@emibcn can you confirm that the way rounding is implemented here is good for you?

And will this be a breaking change for you? If not, I will tag this as `v1`, if yes, I'll add a new `v2` tag.

**Comment by emibcn** [comment]
> @emibcn can you confirm that the way rounding is implemented here is good for you?

Wow!! Wasn't expecting such a change! Great!

**About de precision**: The method to get the rounded number looks goodI think it's better to have 2 outputs: one with all the decimals (for calculations) and another rounded (for pretty printing).

**About the `exit` variable**: it would make sense to me if you output another extra value (for the minimum coverage passed or not). I mean, if you set `percentage: 70` but use `exit: false`, ¿what is the finality of executing the action? If you want to never get the action to failure, you set `percentage: 0` and will still get the output printed in the workflow. Unless you want the action to give a bool output to some next step (for example, [sending a Telegram message](https://github.com/appleboy/telegram-action) and blocking a merge).

**About the Dockerfile**: I think it will be easier to you to use the PHP file `/src/test-coverage-checker.php` directly [as entrypoint of the Docker container](https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/4/files?file-filters%5B%5D=.md&file-filters%5B%5D=.sh&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension#diff-3254677a7917c6c01f55212f86c57fbfL8). This way, [you don't need to install `bash`](https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/4/files#diff-3254677a7917c6c01f55212f86c57fbfL3) and you don't need to add every parameter 3 times (one in the action `inputs` section, another in the action `run` and another one in the entrypoint). You only need to [add the shebang to the file](https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/4/files#diff-25f92ee9cf73708dab21e707fde8d16aR1) and [add execution permissions](https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/4/files?file-filters%5B%5D=.md&file-filters%5B%5D=.sh&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension#diff-25f92ee9cf73708dab21e707fde8d16a) (the commit will save that too).

I have been looking for a library to create GitHub Actions with PHP like the ones in JS (so you can get the `inputs` directly), but haven't found any, yet. Then, we still need to pass each input into the docker args in the `action.yml`. So, writing 2 times each input is the minimum.

> And will this be a breaking change for you? If not, I will tag this as `v1`, if yes, I'll add a new `v2` tag.

This is not a breaking change to me. The amount of lines and the approach have changed both a lot, maybe this is enough to re-tag? I don't know, it's up to you.

**Comment by johanvanhelden** [comment]
Thanks for the feedback @emibcn ! 

I'll try to release this tomorrow or in the weekend with your added suggestions as a  v2 release.

The main reason for the exit option was to allow me to test things with PHPUnit and not having the script actually exit. But a failed boolean output is a great added feature.

I tried using a [shebang](https://github.com/johanvanhelden/gha-clover-test-coverage-check/actions/runs/248248017) and using the php file as an entrypoint, but ended up getting php errors because of the new namespacing. I'd rather have the new namespaced setup and having to declare duplicate inputs vs the old setup. But feel free to try and help me to find a solution 😄

**Comment by emibcn** [comment]
> Thanks for the feedback @emibcn !

Thank you for the job!

> I'll try to release this tomorrow or in the weekend with your added suggestions as a v2 release.

Great!

> The main reason for the exit option was to allow me to test things with PHPUnit and not having the script actually exit. But a failed boolean output is a great added feature.

Fine!

> I tried using a [shebang](https://github.com/johanvanhelden/gha-clover-test-coverage-check/actions/runs/248248017) and using the php file as an entrypoint, but ended up getting php errors because of the new namespacing. I'd rather have the new namespaced setup and having to declare duplicate inputs vs the old setup. But feel free to try and help me to find a solution

Did a pull request over your branch. After re-creating the Docker image, it works:

```shell
$ cat Dockerfile 
FROM php:7.4-alpine

COPY src /src

ENTRYPOINT ["/src/test-coverage-checker.php"]

$ docker build . --tag gha:latest
Sending build context to Docker daemon  402.9kB
Step 1/3 : FROM php:7.4-alpine
 ---> 13b8fc557e7d
Step 2/3 : COPY src /src
 ---> 96a3f8b5e70e
Step 3/3 : ENTRYPOINT ["/src/test-coverage-checker.php"]
 ---> Running in cee988e16801
Removing intermediate container cee988e16801
 ---> cd1b7d411c97
Successfully built cd1b7d411c97
Successfully tagged gha:latest

# Here, the volume is used to contain the XML file
$ docker run --volume $PWD/v:/v:ro gha:latest /v/clover.xml 40 2 true ; echo $?
[ERROR] Code coverage is 38.99%, which is not accepted (>=40%)
##[set-output name=coverage;]38.99
1
```

**Comment by emibcn** [comment]
Ahhh, ok, now I see the workflow output. Ok, let's try another solution.

https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/8/checks?check_run_id=1101926545

**Comment by emibcn** [comment]
Ok, now I've changed the entrypoint to pass all arguments, independently of how many are there, and use [`exec`](https://www.geeksforgeeks.org/exec-command-in-linux-with-examples/) to handle exit status.

**Comment by johanvanhelden** [comment]
Thanks for the PR @emibcn ! It seems to work flawlessly.

The changes have been made.

I decided against using 2 types of values, a rounded one and a non-rounded one, because it could end up confusing people. 

For example: if you set an acceptable percentage of 100, and have an actual coverage of 99.99, what would happen?
The workflow step should fail, because you do not have a 100%, right? But the message output, if you set a precision of 0, would should 100%.

So the rounded value will be used everywhere to keep everything consistent. There will be a display variant in the output, but that will only add the `%`.

And I added the output that can be used to see if the coverage is acceptable or not.

**Comment by johanvanhelden** [comment]
@emibcn 

Thank you for the entrypoint polish, it's a lot better now!

And I am also finished now.

I made all changes fully backward-compatible so I'll just release it on `v1` - this way I am not forcing anyone to update all their workflows to `v2`.

Please check the README for all the new input and output options. I tried to keep it extreme flexible, so people can just use what and how they want.

**Comment by emibcn** [comment]
This is a great job!! Going to update all the workflows where I use it ;)

**Pull request merged**
